name: chelnok_boxing_timer
description: "Chelnok Boxing Timer."
publish_to: 'none'
version: 0.1.1+4


environment:
  sdk: ^3.12.0

dependencies:
  audioplayers: ^6.7.1
  cupertino_native: ^0.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_tts: ^4.2.5
  google_mobile_ads: ^9.0.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  chelnok_vibrate:
    path: packages/chelnok_vibrate

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  


flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
  fonts:
    - family: Alata
      fonts:
        - asset: assets/Alata/Alata-Regular.ttf
